### ISSUE TITLE
Merge Release Candidate into Main Branch

### ISSUE THREAD

**Issue by robmoffat** [finos/FDC3-conformance-framework#209]
- [x] We make sure that all of the 1.2 tests are still working against each desktop agent.   Glue (core), Finsemble, Sail, Connectifi. (@gaganahluwalia)
- [x] Perform the merge (@robmoffat  and @gaganahluwalia )
- [x] Add the 2.0 apps to the FINOS FDC3 App Directory (@robmoffat)
- [x] Test OpenFin still works for 1.2 tests (@gaganahluwalia )
- [x] Tell @openfin-johans that we have the new 2.0 apps in a directory
```[tasklist]
### Tasks
```

**Comment by robmoffat** [comment]
Hi @gaganahluwalia I've just converted into a checklist so we can coordinate on getting this done for Friday.  Give me a buzz if you need any help

**Comment by robmoffat** [comment]
This is on pause until we have Glue working 100%.
